TASK: Markdown processing
sitegeist/Sitegeist.Chatterbox pull request #3
Opened 2024-02-15 12:09 UTC by mficzel

2024-02-20 08:32 UTC, nezaniel requested changes

2024-02-20 08:32 UTC, nezaniel commented on Classes/Domain/ContentCollection.php
> +                $html = $converter->convert($textOrImage->text->value);
I'd move this into a ContentText::fromThreadMessageResponseContentTextObject (or similar) method to be able to instantiate the elements without the necessity of being part of a collection

2024-02-20 08:32 UTC, nezaniel commented on Classes/Domain/ContentText.php
> +    public function getType(): string
What is this method used for?

2024-02-21 14:46 UTC, mficzel commented on Classes/Domain/ContentText.php
> +    public function getType(): string
Damit man im fusion `@if={content.type == 'text'}` machen kann

2024-02-21 15:19 UTC, mficzel commented on Classes/Domain/ContentCollection.php
> +                $html = $converter->convert($textOrImage->text->value);
Adjusted

2024-02-21 15:19 UTC, nezaniel approved these changes

2024-02-21 15:19 UTC, merged